### PR TITLE
Sherlock added

### PR DESCRIPTION
**Pull request by dhruvapte26**
Understood the concepts.Will be adding more series too!

### CODE REVIEW

**Comment by athityakumar** [comment]
@the-ethan-hunt : Running the index.rb now should create sherlock.html in series/ folder. Does it? Include it also in this PR.

**Comment by athityakumar** [comment]
@the-ethan-hunt : Also, add back sherlock.json file too.

**Comment by dhruvapte26** [comment]
Files added and updated as requested

**Comment by athityakumar** [comment]
Merged with my last commit. Delete your fork & re-fork again, for contributing the next series. :smile:

**Pull request closed without merging**
